const multer = require('multer')

const MIME_TYPES = {
    'image/jpg': 'jpg',
    'image/jpeg': 'jpg',
    'image/png': 'png'
}

const storage = multer.diskStorage({
    destination: (req, file, callback) => {
        callback(null, 'images')
    },
    filename: (req, file, callback) => {
        const name = file.originalname.split(' ').join('_')
        const extension = MIME_TYPES[file.mimetype]
        callback(null, name + Date.now() + '.' + extension)
    }
})

module.exports = multer({ storage: storage }).single('uri')

// back
// var fs = require('fs');
// var multer  = require('multer');
// var upload = multer({ dest: 'uploads/' }); //setting the default folder for multer
// //other imports and code will go here
// app.post('/upload',upload.single('fileData'), (req, res,next) => {
//   logger.info(req.file);//this will be automatically set by multer
//   logger.info(req.body);
//   //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
//   fs.readFile(req.file.path,(err, contents)=> {
//    if (err) {
//    console.log('Error: ', err);
//   }else{
//    console.log('File contents ',contents);
//   }
//  });
//});


//front
// import  ImagePicker from 'react-native-image-picker';
//  <!--OTHER CODES and render will go here -->
// <TouchableHiglight onPress={()=>{
// var options = {
//    title: 'Select Image',
//    storageOptions: {
//     skipBackup: true,
//     path: 'images'
//    }
// };
// ImagePicker.showImagePicker(options, (response) => {
//   console.log('Response = ', response);
// if (response.didCancel) {
//   console.log('User cancelled image picker');
// }else if (response.error) {
//  console.log('ImagePicker Error: ', response.error);
// }else if (response.customButton) {
//  console.log('User tapped custom button: ', response.customButton);
// }else {
//  console.log('User selected a file form camera or gallery', response); 
//  const data = new FormData();
//  data.append('name', 'avatar');
//  data.append('fileData', {
//   uri : response.uri,
//   type: response.type,
//   name: response.fileName
//  });
//  const config = {
//   method: 'POST',
//   headers: {
//    'Accept': 'application/json',
//    'Content-Type': 'multipart/form-data',
//   },
//   body: data,
//  };
// fetch("http://localhost:3000/" + "upload", config)
//  .then((checkStatusAndGetJSONResponse)=>{       
//    console.log(checkStatusAndGetJSONResponse);
//  }).catch((err)=>{console.log(err)});
// }
// }}